var num1 = 1;
var str1 = "aa";
var bool1 = true;
var undf = undefined;
var nll = null;
console.log("num1 :>> ", num1);
console.log("str1 :>> ", str1);
console.log("bool1 :>> ", bool1);
console.log("undf :>> ", undf);
console.log("nll :>> ", nll);
console.log("typeof 1 :>> ", typeof 1);
console.log('typeof "a" :>> ', typeof "a");
console.log("typeof true :>> ", typeof true);
console.log("typeof undefined :>> ", typeof undefined);
console.log("typeof null :>> ", typeof null);
console.log("typeof NaN :>> ", typeof NaN);
console.log("typeof Infinity :>> ", typeof Infinity);
console.log('1 / "2" :>> ', 1 / "2");
console.log('"2"/3 :>> ', "2" / 3);
